routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

/*
|--------------------------------------------------------------------------
| Members Route
|--------------------------------------------------------------------------
*/
Route::prefix('members')->group(function () {

    Route::get('/all', 'UsersController@allMembers')->name('members.all');
    Route::get('/add', 'UsersController@addMember')->name('members.add');
    Route::post('/save', 'UsersController@saveMember')->name('members.save');
    Route::get('/{member}/edit', 'UsersController@editMember')->name('members.edit');
    Route::post('/{member}/update', 'UsersController@updateMember')->name('members.update');
    Route::post('/{member}/switch-status', 'UsersController@switchMemberStatus')->name('members.status.switch');

});

/*
|--------------------------------------------------------------------------
| Publishers Route
|--------------------------------------------------------------------------
*/
Route::prefix('publishers')->group(function () {

    Route::get('/all', 'PublishersController@all')->name('publishers.all');
    Route::get('/add', 'PublishersController@add')->name('publishers.add');
    Route::post('/save', 'PublishersController@save')->name('publishers.save');
    Route::get('/{publisher}/edit', 'PublishersController@edit')->name('publishers.edit');
    Route::post('/{publisher}/update', 'PublishersController@update')->name('publishers.update');

});

/*
|--------------------------------------------------------------------------
| Authors Route
|--------------------------------------------------------------------------
*/
Route::prefix('authors')->group(function () {

    Route::get('/all', 'AuthorsController@all')->name('authors.all');
    Route::get('/add', 'AuthorsController@add')->name('authors.add');
    Route::post('/save', 'AuthorsController@save')->name('authors.save');
    Route::get('/{author}/edit', 'AuthorsController@edit')->name('authors.edit');
    Route::post('/{author}/update', 'AuthorsController@update')->name('authors.update');

});

/*
|--------------------------------------------------------------------------
| Shelves Route
|--------------------------------------------------------------------------
*/
Route::prefix('shelves')->group(function () {

    Route::get('/all', 'ShelvesController@all')->name('shelves.all');
    Route::get('/add', 'ShelvesController@add')->name('shelves.add');
    Route::post('/save', 'ShelvesController@save')->name('shelves.save');
    Route::get('/{shelf}/edit', 'ShelvesController@edit')->name('shelves.edit');
    Route::post('/{shelf}/update', 'ShelvesController@update')->name('shelves.update');

});

/*
|--------------------------------------------------------------------------
| Categories Route
|--------------------------------------------------------------------------
*/
Route::prefix('categories')->group(function () {

    Route::get('/all', 'CategoriesController@all')->name('categories.all');
    Route::get('/add', 'CategoriesController@add')->name('categories.add');
    Route::post('/save', 'CategoriesController@save')->name('categories.save');
    Route::get('/{category}/edit', 'CategoriesController@edit')->name('categories.edit');
    Route::post('/{category}/update', 'CategoriesController@update')->name('categories.update');

});

/*
|--------------------------------------------------------------------------
| Books Route
|--------------------------------------------------------------------------
*/
Route::prefix('books')->group(function () {

    Route::get('/all', 'BooksController@all')->name('books.all');
    Route::get('/add', 'BooksController@add')->name('books.add');
    Route::post('/save', 'BooksController@save')->name('books.save');
    Route::get('/{book}/edit', 'BooksController@edit')->name('books.edit');
    Route::post('/{book}/update', 'BooksController@update')->name('books.update');
    Route::get('/{book}/count/add', 'BooksController@addCountForm')->name('books.count.add');
    Route::post('/{book}/count/add', 'BooksController@addCount')->name('books.count.add');
});

/*
|--------------------------------------------------------------------------
| Borrow Route
|--------------------------------------------------------------------------
*/
Route::prefix('borrowed-book')->group(function () {

    Route::get('/all', 'BorrowedBooksController@all')->name('borrow.all');
    Route::get('/new/{user?}', 'BorrowedBooksController@new')->name('borrow.new');
    Route::post('/save/{user}', 'BorrowedBooksController@save')->name('borrow.save');
    Route::get('/edit/{borrow}', 'BorrowedBooksController@edit')->name('borrow.edit');
    Route::post('/update/{borrow}', 'BorrowedBooksController@update')->name('borrow.update');

    Route::get('/books/fetch', 'BorrowedBooksController@fetchBooks')->name('borrow.books.fetch');

});

app/Models/Borrow.php
<?php

namespace Librory\Models;

use Illuminate\Database\Eloquent\Model;

class Borrow extends Model
{
    protected $fillable = [
        'user_id',
        'librorian_id',
        'return_date',
        'status',
    ];

    protected $dates = [
        'return_date'
    ];

    /**
     * -------------------------------------------------------------------------
     * Relationship functions
     * -------------------------------------------------------------------------
     */

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function librorian()
    {
        return $this->belongsTo(User::class, 'librorian_id', 'id');
    }

    public function borrowedBooks()
    {
        return $this->hasMany(BorrowedBook::class, 'borrow_id', 'id');
    }

    public function books()
    {
        return $this->belongsToMany(Book::class, 'borrowed_books', 'borrow_id', 'book_id');
    }

    /**
     * -------------------------------------------------------------------------
     * Accessor functions
     * -------------------------------------------------------------------------
     */

    public function getBookIdsAttribute()
    {
        if (count($this->books) > 0) {
            return $this->books->pluck('id')->toArray();
        }

        return [];
    }

    /**
     * -------------------------------------------------------------------------
     * Route functions
     * -------------------------------------------------------------------------
     */

    public function editUrl()
    {
        return route('borrow.edit', [
            'borrow' => $this->id
        ]);
    }

    public function updateUrl()
    {
        return route('borrow.update', [
            'borrow' => $this->id
        ]);
    }

    /**
     * -------------------------------------------------------------------------
     * Unsorted functions
     * -------------------------------------------------------------------------
     */

    public function linkBooks($books)
    {
        if (count($this->borrowedBooks) > 0) {
            $this->borrowedBooks()->delete();
        }

        $books = Book::whereIn('id', $books)->get();

        $data = [];
        foreach ($books as $book) {
            if ($book->total_count == 0) {
                continue;
            }
            array_push($data, [
                'borrow_id' => $this->id,
                'book_id' => $book->id
            ]);
        }

        BorrowedBook::insert($data);
    }

    public function has($book)
    {
        return in_array($book->id, $this->book_ids);
    }
}

app/Http/Controllers/BorrowedBooksController.php
<?php

namespace Librory\Http\Controllers;

use Librory\Models\Book;
use Librory\Models\User;
use Librory\Models\Borrow;
use Illuminate\Http\Request;
use Librory\Http\Requests\NewBorrowRequest;
use Librory\Http\Requests\EditBorrowRequest;

class BorrowedBooksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('librorian');
    }

    public function all()
    {
        $borrowedBooks = Borrow::withCount('books')
            ->latest()
            ->paginate(15);

        return view('pages.borrows.all', compact(
            'borrowedBooks'
        ));
    }

    public function new(User $user)
    {
        if (! $user->id) {
            $members = User::members(true)
                ->orderBy('last_name')
                ->get();

            return view('pages.borrows.select-member', compact(
                'members'
            ));
        }

        return view('pages.borrows.new', compact(
            'user'
        ));
    }

    public function save(NewBorrowRequest $request, User $user)
    {
        $borrowedBook = Borrow::create([
            'user_id' => $user->id,
            'librorian_id' => auth()->id(),
            'return_date' => $request->return_date
        ]);

        $borrowedBook->linkBooks($request->books);

        return redirect()->route('borrow.all')
            ->withStatus('Success!');
    }

    public function edit(Borrow $borrow)
    {
        $user = $borrow->user;
        $borrow->load('books');

        return view('pages.borrows.edit', compact(
            'borrow',
            'user'
        ));
    }

    public function update(EditBorrowRequest $request, Borrow $borrow)
    {
        $borrow->update([
            'return_date' => $request->return_date
        ]);

        $borrow->linkBooks($request->books);

        return redirect()->route('borrow.all')
            ->withStatus('Updated successfully!');
    }

    public function fetchBooks()
    {
        $books = Book::orderByTitle();
        $books->load('authors', 'counts', 'borrowed', 'borrowed.borrow');

        $ids = [];
        if (request()->has('books') and ! is_null(request()->books)) {
            $ids = explode(',', request()->books);
        }

        $borrow = null;
        if (request()->has('borrow') and ! is_null(request()->borrow)) {
            $borrow = Borrow::find(request()->borrow);
            $borrow->load('books');
        }

        return response()->json([
            'count' => count($books),
            'list' => view('pages.borrows.books-list', compact(
                'books',
                'borrow',
                'ids'
            ))->render()
        ]);
    }
}

resources/views/pages/borrows/all.blade.php
@extends('layouts.app')

@section('page-title', 'Borrowed Books')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">

            <div class="page-header">
                <h2>Borrowed Books</h2>
            </div>

            <div class="page-actions">
                <a href="{{ route('borrow.new') }}" class="btn btn-primary">
                    New Borrow
                </a>
            </div>

            <table class="table table-bb">
                <thead>
                    <tr>
                        <th scope="col">Member</th>
                        <th scope="col">Books</th>
                        <th scope="col">Status</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Date Returned</th>
                        <th class="text-right">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($borrowedBooks as $borrowedBook)
                        @include('pages.borrows.row')
                    @empty
                        <tr>
                            <td colspan="5" class="text-center active noselect">
                                No borrowed books yet
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>

            <div class="list-pagination">
                {{ $borrowedBooks->links() }}
            </div>

        </div>
    </div>
</div>
@endsection

@section('footer-addon')
<script>
$(function () {

    @include('components.status')

});
</script>
@endsection

resources/views/pages/borrows/books-list.blade.php
<ul class="list-group">
    @forelse ($books as $book)
        @php
            $availableQuantity = $book->total_available;
            if (isset($borrow) and $borrow and $borrow->has($book)) {
                $availableQuantity++;
            }
        @endphp
        @if ($availableQuantity > 0)
            <li class="list-group-item">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input"
                        id="book-{{ $book->id }}" value="{{ $book->id }}" name="books[]"
                        @if (in_array($book->id, $ids)) checked @endif
                    />
                    <label class="custom-control-label d-block" for="book-{{ $book->id }}">
                        <span class="float-right ml-3">
                            <strong>{{ $availableQuantity }}</strong>
                        </span>
                        <span class="text-primary">
                            {{ $book->title }}
                        </span>
                        @if (count($book->authors) > 0)
                            <br />
                            <small>
                                @foreach ($book->authors as $author)
                                    @if (! $loop->first), @endif
                                    {{ $author->name }}
                                @endforeach
                            </small>
                        @endif
                    </label>
                </div>
            </li>
        @endif
    @empty
        <li class="list-group-item noselect">
            No available books
        </li>
    @endforelse
</ul>

resources/views/pages/borrows/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Borrowed Books')
@section('body-class', 'w-fixed-sidebar')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">

            <div class="page-header">
                <h5>Member's Info</h5>
                <h2>{{ $user->name }}</h2>

                <article class="pt-2">
                    {{ $user->contact_number }} &middot; {{ $user->email }}
                </article>
            </div>

            <form action="{{ $borrow->updateUrl() }}" method="post" autocomplete="off">

                <div class="fixed-sidebar">
                    <div id="books-list"
                        data-url="{{ route('borrow.books.fetch', [
                            'borrow' => $borrow->id,
                            'books' => implode(',', $borrow->book_ids)
                        ]) }}">
                        <i class="fas fa-circle-notch fa-spin text-primary"></i>&nbsp; Fetching Books
                    </div>
                </div>

                <div class="form-group last">
                    <label for="b-return-date">Return Date</label>
                    <input type="date" id="b-return-date" name="return_date"
                        class="form-control" required
                        min="{{ \Carbon\Carbon::now()->addDay()->toDateString() }}"
                        value="{{ old('return_date', $borrow->return_date->toDateString()) }}"
                    />
                </div>

                <div class="form-group buttons">
                    <button type="submit" class="btn btn-primary">Submit Changes</button>
                    <a href="{{ route('borrow.all') }}" class="btn btn-link">Cancel</a>
                </div>

            {!! csrf_field() !!}
            </form>

        </div>
    </div>
</div>
@endsection

@section('footer-addon')
<script>
$(function () {

    @include('components.status')

    fetchBooks();

});

function fetchBooks()
{
    var container = $('#books-list'),
        url = container.data('url');

    $.get(url)
        .done(function (r) {
            if (r.count > 0) {
                container.html(r.list);
            }
        })
        .fail(function (r) {
            container.html('Error while trying to fetch books.');
        });
}
</script>
@endsection

resources/views/pages/borrows/new.blade.php
@extends('layouts.app')

@section('page-title', 'Borrowed Books')
@section('body-class', 'w-fixed-sidebar')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">

            <div class="page-header">
                <h5>Member's Info</h5>
                <h2>{{ $user->name }}</h2>

                <article class="pt-2">
                    {{ $user->contact_number }} &middot; {{ $user->email }}
                </article>
            </div>

            <form action="{{ route('borrow.save', ['user' => $user->id]) }}" method="post" autocomplete="off">

                <div class="fixed-sidebar">
                    <div id="books-list" data-url="{{ route('borrow.books.fetch') }}">
                        <i class="fas fa-circle-notch fa-spin text-primary"></i>&nbsp; Fetching Books
                    </div>
                </div>

                <div class="form-group last">
                    <label for="b-return-date">Return Date</label>
                    <input type="date" id="b-return-date" name="return_date"
                        class="form-control" required
                        min="{{ \Carbon\Carbon::now()->addDay()->format('Y-m-d') }}"
                        value="{{ old('return_date') }}"
                    />
                </div>

                <div class="form-group buttons">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{ route('borrow.all') }}" class="btn btn-link">Cancel</a>
                </div>

            {!! csrf_field() !!}
            </form>

        </div>
    </div>
</div>
@endsection

@section('footer-addon')
<script>
$(function () {

    @include('components.status')

    fetchBooks();

});

function fetchBooks()
{
    var container = $('#books-list'),
        url = container.data('url');

    $.get(url)
        .done(function (r) {
            if (r.count > 0) {
                container.html(r.list);
            }
        })
        .fail(function (r) {
            container.html('Error while trying to fetch books.');
        });
}
</script>
@endsection

resources/views/pages/borrows/row.blade.php
<tr id="borrow-{{ $borrowedBook->id }}">
    <td>
        <a href="#">
            <strong>{{ $borrowedBook->user->name }}</strong>
        </a>
    </td>
    <td>
        <a href="#">
            {{ $borrowedBook->books_count }}
        </a>
    </td>
    <td>
        {{ ucwords($borrowedBook->status) }}
    </td>
    <td>
        {{ $borrowedBook->return_date->format('F j, Y') }}
    </td>
    <td></td>
    <td class="text-right">
        <a href="{{ $borrowedBook->editUrl() }}">
            <i class="fas fa-pencil-alt fa-fw"></i>
        </a>
        <a href="#">
            <i class="fas fa-ellipsis-h fa-fw"></i>
        </a>
    </td>
</tr>

resources/views/pages/borrows/select-member.blade.php
@extends('layouts.app')

@section('page-title', 'Select Member')

@section('head-addon')
<style>
    .list-group-item {
        cursor: pointer;
    }
</style>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">

            <div class="d-flex justify-content-center">
            <div class="form-container">

                <div class="page-header">
                    <h3>Select Member</h3>
                </div>

                <div class="list-group">
                    @forelse ($members as $member)
                        <a href="{{ $member->newBorrowBookUrl() }}" class="list-group-item list-group-item-action">
                            {{ $member->name }}
                        </a>
                    @empty
                        <li class="list-group-item disabled">
                            No members yet
                        </li>
                    @endforelse
                </div>

            </div>
            </div>

        </div>
    </div>
</div>
@endsection

@section('footer-addon')
<script>
$(function () {

    // $(document)

});
</script>
@endsection